# Generated by Django 5.2.13 on 2026-06-09 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_title', models.CharField(max_length=255, verbose_name='제목')),
                ('source_url', models.CharField(max_length=500, verbose_name='원문 URL')),
                ('collected_at', models.DateTimeField(verbose_name='수집 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신 일시')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='raw_datas', to='users.category')),
            ],
            options={
                'verbose_name': 'Raw Data',
                'verbose_name_plural': 'Raw Datas',
                'db_table': 'RAW_DATAS',
            },
        ),
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('news', 'News'), ('policy', 'Policy')], max_length=10, verbose_name='카드 종류')),
                ('card_title', models.CharField(max_length=255, verbose_name='제목')),
                ('intro', models.CharField(max_length=255, verbose_name='한 줄 소개')),
                ('summary', models.TextField(verbose_name='요약')),
                ('core_content', models.TextField(verbose_name='핵심 내용')),
                ('perspectives', models.TextField(verbose_name='다양한 입장')),
                ('debate_topic', models.TextField(blank=True, null=True, verbose_name='토론 주제 (뉴스 카드 전용)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발행 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신 일시')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='users.category')),
            ],
            options={
                'verbose_name': 'Info Card',
                'verbose_name_plural': 'Info Cards',
                'db_table': 'INFO_CARDS',
            },
        ),
        migrations.CreateModel(
            name='RawArticle',
            fields=[
                ('data', models.OneToOneField(db_column='data_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='article', serialize=False, to='cards.rawdata')),
                ('press', models.CharField(max_length=100, verbose_name='언론사명')),
                ('published_at', models.DateField(verbose_name='기사 발행일')),
            ],
            options={
                'verbose_name': 'Raw Article',
                'verbose_name_plural': 'Raw Articles',
                'db_table': 'RAW_ARTICLES',
            },
        ),
        migrations.CreateModel(
            name='RawPolicy',
            fields=[
                ('data', models.OneToOneField(db_column='data_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='policy', serialize=False, to='cards.rawdata')),
                ('department', models.CharField(max_length=100, verbose_name='소관부처')),
                ('apply_period', models.TextField(verbose_name='신청기한')),
                ('policy_law', models.TextField(blank=True, null=True, verbose_name='근거법령')),
            ],
            options={
                'verbose_name': 'Raw Policy',
                'verbose_name_plural': 'Raw Policies',
                'db_table': 'RAW_POLICIES',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='북마크 설정 일시')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('card', models.ForeignKey(db_column='card_id', on_delete=django.db.models.deletion.CASCADE, to='cards.infocard')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'db_table': 'BOOKMARKS',
                'unique_together': {('user', 'card')},
            },
        ),
    ]
