# Generated by Django 5.2.13 on 2026-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocard',
            name='source_urls',
            field=models.TextField(default='[]', verbose_name='출처 URL 목록'),
        ),
    ]
