# Generated by Django 5.2.13 on 2026-06-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, verbose_name='카테고리 이름')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'CATEGORIES',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(db_column='region_id', primary_key=True, serialize=False)),
                ('sido', models.CharField(max_length=25, verbose_name='광역시도')),
                ('sigungu', models.CharField(max_length=15, verbose_name='시군구')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'REGIONS',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호 해시')),
                ('nickname', models.CharField(max_length=40, verbose_name='닉네임')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='계정 수정 일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='회원탈퇴 일시')),
                ('age', models.PositiveSmallIntegerField(verbose_name='나이')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6, verbose_name='성별')),
                ('login_fail_count', models.SmallIntegerField(default=0, verbose_name='로그인 실패 횟수')),
                ('is_temp_password', models.SmallIntegerField(default=0, verbose_name='임시 비밀번호 여부')),
                ('foul_count', models.SmallIntegerField(default=0, verbose_name='욕설 사용 횟수')),
                ('region', models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.region', verbose_name='거주지')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'USERS',
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('interest_id', models.AutoField(db_column='interest_id', primary_key=True, serialize=False)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='users.category', verbose_name='카테고리')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='users.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'User Interest',
                'verbose_name_plural': 'User Interests',
                'db_table': 'USER_INTERESTS',
            },
        ),
    ]
