# Generated by Django 4.2.30 on 2026-06-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_user_unique_active_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_temp_password',
        ),
    ]
