# Generated by Django 5.2.13 on 2026-06-09 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateSession',
            fields=[
                ('debate_session_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_round', models.CharField(choices=[('1', '입장 제시'), ('2', '찬성 세부주장'), ('3', '반대 세부주장'), ('4', '주장 다지기')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(db_column='card_id', on_delete=django.db.models.deletion.PROTECT, to='cards.infocard')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='users.user')),
            ],
            options={
                'db_table': 'DEBATE_SESSIONS',
            },
        ),
        migrations.CreateModel(
            name='DebateMessage',
            fields=[
                ('debate_msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'User'), ('AI', 'AI')], max_length=4)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('PRO', '찬성'), ('CON', '반대'), ('QUESTION', '질문'), ('ANSWER', '답변')], max_length=8)),
                ('debate_session', models.ForeignKey(db_column='debate_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='debates.debatesession')),
            ],
            options={
                'db_table': 'DEBATE_MESSAGES',
                'ordering': ['created_at'],
            },
        ),
    ]