# Generated by Django 5.2.13 on 2026-06-09 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('chat_msg_id', models.AutoField(db_column='chat_msg_id', primary_key=True, serialize=False)),
                ('input', models.TextField(verbose_name='유저 입력')),
                ('output', models.TextField(verbose_name='AI 출력 / 에러 메시지')),
                ('is_memory', models.SmallIntegerField(verbose_name='메모리 사용 여부 (0=사용, 1=미사용)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='메시지 발송 일시')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'CHAT_MESSAGES',
            },
        ),
        migrations.CreateModel(
            name='ChatMsgCard',
            fields=[
                ('chat_msg_card_id', models.AutoField(db_column='chat_msg_card_id', primary_key=True, serialize=False)),
                ('is_selected', models.SmallIntegerField(verbose_name='사용자 카드 선택 여부')),
                ('card', models.ForeignKey(db_column='card_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_msg_cards', to='cards.infocard', verbose_name='정보 카드')),
                ('chat_message', models.ForeignKey(db_column='chat_msg_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_cards', to='chatbot.chatmessage', verbose_name='채팅 메시지')),
            ],
            options={
                'verbose_name': 'Chat Msg Card',
                'verbose_name_plural': 'Chat Msg Cards',
                'db_table': 'CHAT_MSG_CARDS',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('chat_session_id', models.AutoField(db_column='chat_session_id', primary_key=True, serialize=False)),
                ('session_title', models.CharField(max_length=255, verbose_name='세션 타이틀')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='세션 개설 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='세션 갱신 일시')),
                ('is_delete', models.SmallIntegerField(default=0, verbose_name='삭제 여부')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='users.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'CHAT_SESSIONS',
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_session',
            field=models.ForeignKey(db_column='chat_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession', verbose_name='채팅 세션'),
        ),
        migrations.CreateModel(
            name='ChatSummary',
            fields=[
                ('chat_summary_id', models.AutoField(db_column='chat_summary_id', primary_key=True, serialize=False)),
                ('chat_summary', models.TextField(verbose_name='대화 요약')),
                ('is_memory', models.SmallIntegerField(verbose_name='사용 상태 (0=사용중, 1=미사용)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요약 생성 일시')),
                ('chat_session', models.ForeignKey(db_column='chat_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='chatbot.chatsession', verbose_name='채팅 세션')),
            ],
            options={
                'verbose_name': 'Chat Summary',
                'verbose_name_plural': 'Chat Summaries',
                'db_table': 'CHAT_SUMMARIES',
            },
        ),
    ]
